# Generated by Django 2.0.7 on 2018-08-15 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='comment2',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.CharField(max_length=256),
        ),
    ]
