# Generated by Django 2.0.7 on 2018-08-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180815_0512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment2',
            old_name='img',
            new_name='image',
        ),
    ]
