# Generated by Django 2.0.7 on 2018-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180815_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
