# Generated by Django 2.0.7 on 2018-08-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180815_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='content',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category2',
            name='img',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
