# Generated by Django 2.0.7 on 2018-08-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180815_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='category2',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
