# Generated by Django 2.0.7 on 2018-08-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category2_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=256)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
