# Generated by Django 2.0.7 on 2018-08-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_ly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
