# Generated by Django 2.0.7 on 2018-08-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_article_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='category2',
            old_name='count',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='like',
            new_name='likes',
        ),
    ]
